# Generated by Django 3.1.3 on 2022-10-06 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_auto_20221005_0748'),
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsFeeds',
            new_name='NewsFeed',
        ),
    ]
